### ISSUE TITLE
Interfacing with Python

### ISSUE THREAD

**Issue by Amyantis** [GregLando113/GWCA#31]
Hi,

I would like to use this GW client using Python. Is it theoretically possible to interface GWCA C++ functions in a piece of Python code?

Thank you.

**Comment by 3vcloud** [comment]
You can compile and run GWCA with a compiler option to expose the function calls in the dll, then call them from your python script

https://github.com/GregLando113/GWCA/blob/master/Include/GWCA/Utilities/Export.h

**Comment by ldufr** [comment]
So it's not something we will do and it's a bit more complicated than what 3vcloud proposed. If you want to call the function directly, you will need to have your python interpret running in Guild Wars process which require some work. Otherwise, you can create a server that uses GWCA, inject it in Guild Wars and finally communicate with it through named pipes or sockets.
